wandb_version: 1

batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 100
num_workers:
  desc: null
  value: 2
embed_size:
  desc: null
  value: 64
layers_num:
  desc: null
  value: 4
heads_num:
  desc: null
  value: 8
cuda:
  desc: null
  value: 0
lr:
  desc: null
  value: 2.0e-05
seed:
  desc: null
  value: 3704
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725342266
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 17
      - 23
      - 37
      4: 3.10.14
      5: 0.17.8
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
